name: Build Release APK

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build release APK
        env:
          SPARK_API_KEY: ${{ secrets.SPARK_API_KEY }}
        run: ./gradlew :app:assembleRelease
